export const settingsExtraSchemaSelector = "[data-schema-extra]";

export const settingsSectionSchema = {
  target: { section: "receiver", title: "分享目标设置" },
  basic: { section: "basic_conf" },
  sequence: {
    section: "basic_conf",
    title: "全局时段序列",
    hint: "当本次分享类型为自动时，会按当前时段的序列循环选择分享类型；智能定时若指定具体类型，会优先使用计划类型。",
  },
  briefing: { section: "extra_shares" },
  content: { section: "content_library" },
  context: { section: "context_conf" },
  news: { section: "news_conf" },
  media: { section: "image_conf" },
  tts: { section: "tts_conf" },
  weixin: {
    section: "image_conf",
    title: "个人微信图片",
    hint: "这些选项只影响个人微信图片发送前的压缩、超时和临时文件清理。",
  },
  qzone: { section: "qzone_conf" },
  qzoneSequence: {
    section: "qzone_conf",
    title: "QQ空间时段序列",
    hint: "当本次说说类型为自动时，会按当前时段的序列循环选择说说类型；智能定时若指定具体类型，会优先使用计划类型。",
  },
};

export const settingsFieldSchema = {
  cfgEnabled: { root: "enable_auto_share" },
  cfgTargetGroups: { section: "receiver", field: "groups" },
  cfgTargetUsers: { section: "receiver", field: "users" },
  cfgContactAliases: { root: "contact_aliases" },
  cfgBasicTriggerMode: { section: "basic_conf", field: "trigger_mode" },
  cfgBasicFixedTimes: { section: "basic_conf", field: "fixed_times" },
  cfgBasicShareCron: { section: "basic_conf", field: "share_cron" },
  cfgBasicRandomPeriods: { section: "basic_conf", field: "random_periods" },
  cfgBasicSmartMaxCount: { section: "basic_conf", field: "smart_schedule_max_count" },
  cfgBasicSmartQuietHours: { section: "basic_conf", field: "smart_schedule_quiet_hours" },
  cfgBasicSmartPrompt: { section: "basic_conf", field: "smart_schedule_prompt" },
  cfgBasicCronDelay: { section: "basic_conf", field: "cron_random_delay" },
  cfgBasicShareType: { section: "basic_conf", field: "share_type" },
  cfgBasicShareOutputFormat: { section: "basic_conf", field: "share_output_format" },
  cfgBasicRetentionDays: { section: "basic_conf", field: "data_retention_days" },
  cfgBasicDynamicDays: { section: "basic_conf", field: "dashboard_dynamic_days" },
  cfgDawnSequence: { section: "basic_conf", field: "dawn_sequence" },
  cfgMorningSequence: { section: "basic_conf", field: "morning_sequence" },
  cfgForenoonSequence: { section: "basic_conf", field: "forenoon_sequence" },
  cfgNoonSequence: { section: "basic_conf", field: "noon_sequence" },
  cfgAfternoonSequence: { section: "basic_conf", field: "afternoon_sequence" },
  cfgEveningSequence: { section: "basic_conf", field: "evening_sequence" },
  cfgNightSequence: { section: "basic_conf", field: "night_sequence" },
  cfgLateNightSequence: { section: "basic_conf", field: "late_night_sequence" },
  cfgReferenceHistoryCount: { section: "context_conf", field: "reference_history_count" },
  cfgLifeContext: { section: "context_conf", field: "enable_life_context" },
  cfgLifeContextGroup: { section: "context_conf", field: "life_context_in_group" },
  cfgGroupSchedule: { section: "context_conf", field: "group_share_schedule" },
  cfgChatHistory: { section: "context_conf", field: "enable_chat_history" },
  cfgDeepHistory: { section: "context_conf", field: "enable_deep_history" },
  cfgDeepHistoryHours: { section: "context_conf", field: "deep_history_hours" },
  cfgDeepHistoryMaxCount: { section: "context_conf", field: "deep_history_max_count" },
  cfgPrivateHistoryCount: { section: "context_conf", field: "private_history_count" },
  cfgGroupIntensityCount: { section: "context_conf", field: "group_intensity_check_count" },
  cfgGroupShareStrategy: { section: "context_conf", field: "group_share_strategy" },
  cfgRecordMemory: { section: "context_conf", field: "record_share_to_memory" },
  cfgBriefingGroups: { section: "extra_shares", field: "briefing_groups" },
  cfgBriefingUsers: { section: "extra_shares", field: "briefing_users" },
  cfgBriefing60s: { section: "extra_shares", field: "enable_60s_news" },
  cfgBriefingAi: { section: "extra_shares", field: "enable_ai_news" },
  cfgBriefingQzoneSync: { section: "extra_shares", field: "sync_briefing_to_qzone" },
  cfgBriefingScheduleMode: { section: "extra_shares", field: "briefing_schedule_mode" },
  cfgBriefingFixedTimes: { section: "extra_shares", field: "briefing_fixed_times" },
  cfgBriefingRandomPeriods: { section: "extra_shares", field: "briefing_random_periods" },
  cfgBriefingCron: { section: "extra_shares", field: "cron_briefing" },
  cfgBriefingSmartMaxCount: { section: "extra_shares", field: "briefing_smart_schedule_max_count" },
  cfgBriefingSmartQuietHours: { section: "extra_shares", field: "briefing_smart_schedule_quiet_hours" },
  cfgBriefingSmartPrompt: { section: "extra_shares", field: "briefing_smart_schedule_prompt" },
  cfgBriefingDelay: { section: "extra_shares", field: "briefing_cron_random_delay" },
  cfgQzoneEnabled: { section: "qzone_conf", field: "enable_qzone" },
  cfgQzoneTimeout: { section: "qzone_conf", field: "qzone_api_timeout_seconds" },
  cfgQzoneTriggerMode: { section: "qzone_conf", field: "qzone_trigger_mode" },
  cfgQzoneFixedTimes: { section: "qzone_conf", field: "qzone_fixed_times" },
  cfgQzoneCron: { section: "qzone_conf", field: "qzone_cron" },
  cfgQzoneDelay: { section: "qzone_conf", field: "qzone_cron_random_delay" },
  cfgQzoneRandomPeriods: { section: "qzone_conf", field: "qzone_random_periods" },
  cfgQzoneSmartMaxCount: { section: "qzone_conf", field: "qzone_smart_schedule_max_count" },
  cfgQzoneSmartQuietHours: { section: "qzone_conf", field: "qzone_smart_schedule_quiet_hours" },
  cfgQzoneSmartPrompt: { section: "qzone_conf", field: "qzone_smart_schedule_prompt" },
  cfgQzoneShareType: { section: "qzone_conf", field: "qzone_share_type" },
  cfgQzoneShareOutputFormat: { section: "qzone_conf", field: "qzone_share_output_format" },
  cfgQzoneImage: { section: "qzone_conf", field: "qzone_enable_image" },
  cfgQzoneHotImage: { section: "qzone_conf", field: "qzone_attach_hot_news_image" },
  cfgQzoneImageTypes: { section: "qzone_conf", field: "qzone_image_enabled_types" },
  cfgQzoneAutoInteraction: { section: "qzone_conf", field: "qzone_enable_auto_interaction" },
  cfgQzoneAutoInteractionCron: { section: "qzone_conf", field: "qzone_auto_interaction_cron" },
  cfgQzoneAutoLike: { section: "qzone_conf", field: "qzone_enable_auto_like" },
  cfgQzoneAutoLikeLimit: { section: "qzone_conf", field: "qzone_auto_like_limit" },
  cfgQzoneAutoComment: { section: "qzone_conf", field: "qzone_enable_auto_comment" },
  cfgQzoneAutoCommentLimit: { section: "qzone_conf", field: "qzone_auto_comment_limit" },
  cfgQzoneAutoCommentPrompt: { section: "qzone_conf", field: "qzone_auto_comment_prompt" },
  cfgQzoneAutoReply: { section: "qzone_conf", field: "qzone_enable_auto_reply" },
  cfgQzoneAutoReplyLimit: { section: "qzone_conf", field: "qzone_auto_reply_limit" },
  cfgQzoneAutoReplyPrompt: { section: "qzone_conf", field: "qzone_auto_reply_prompt" },
  cfgQzoneDawnSequence: { section: "qzone_conf", field: "qzone_dawn_sequence" },
  cfgQzoneMorningSequence: { section: "qzone_conf", field: "qzone_morning_sequence" },
  cfgQzoneForenoonSequence: { section: "qzone_conf", field: "qzone_forenoon_sequence" },
  cfgQzoneNoonSequence: { section: "qzone_conf", field: "qzone_noon_sequence" },
  cfgQzoneAfternoonSequence: { section: "qzone_conf", field: "qzone_afternoon_sequence" },
  cfgQzoneEveningSequence: { section: "qzone_conf", field: "qzone_evening_sequence" },
  cfgQzoneNightSequence: { section: "qzone_conf", field: "qzone_night_sequence" },
  cfgQzoneLateNightSequence: { section: "qzone_conf", field: "qzone_late_night_sequence" },
  cfgKnowledgePrefix: { section: "content_library", field: "show_knowledge_type_prefix" },
  cfgRecPrefix: { section: "content_library", field: "show_rec_type_prefix" },
  cfgKnowledgeCats: { section: "content_library", field: "knowledge_cats" },
  cfgRecCats: { section: "content_library", field: "rec_cats" },
  cfgAiImage: { section: "image_conf", field: "enable_ai_image" },
  cfgHotImage: { section: "image_conf", field: "attach_hot_news_image" },
  cfgNewsImageCleanupMax: { section: "image_conf", field: "news_image_cleanup_max_count" },
  cfgPriorityText: { section: "image_conf", field: "priority_text_over_schedule" },
  cfgAiVideo: { section: "image_conf", field: "enable_ai_video" },
  cfgSeparateMedia: { section: "image_conf", field: "separate_text_and_image" },
  cfgSeparateDelay: { section: "image_conf", field: "separate_send_delay" },
  cfgRecordImageDesc: { section: "image_conf", field: "record_image_description" },
  cfgAlwaysSelf: { section: "image_conf", field: "image_always_include_self" },
  cfgNeverSelf: { section: "image_conf", field: "image_never_include_self" },
  cfgImageTypes: { section: "image_conf", field: "image_enabled_types" },
  cfgVideoTypes: { section: "image_conf", field: "video_enabled_types" },
  cfgAppearancePrompt: { section: "image_conf", field: "appearance_prompt" },
  cfgTtsEnabled: { section: "tts_conf", field: "enable_tts" },
  cfgAudioOnly: { section: "tts_conf", field: "prefer_audio_only" },
  cfgTtsTypes: { section: "tts_conf", field: "tts_enabled_types" },
  cfgWeixinCompress: { section: "image_conf", field: "weixin_compress_images" },
  cfgWeixinMaxSide: { section: "image_conf", field: "weixin_image_max_side" },
  cfgWeixinMaxSize: { section: "image_conf", field: "weixin_image_max_size_kb" },
  cfgWeixinTimeout: { section: "image_conf", field: "weixin_api_timeout_seconds" },
  cfgWeixinCleanupMax: { section: "image_conf", field: "weixin_temp_cleanup_max_count" },
  cfgNewsApiEnabled: { section: "news_conf", field: "enable_news_api" },
  cfgNewsApiKey: { section: "news_conf", field: "nycnm_api_key" },
  cfgNewsMode: { section: "news_conf", field: "news_random_mode" },
  cfgNewsFixedSource: { section: "news_conf", field: "news_api_source" },
  cfgNewsItemsCount: { section: "news_conf", field: "news_items_count" },
  cfgNewsShareCount: { section: "news_conf", field: "news_share_count" },
  cfgNewsApiTimeout: { section: "news_conf", field: "news_api_timeout" },
  cfgNewsWebSearch: { section: "news_conf", field: "enable_web_search" },
  cfgNewsRandomSources: { section: "news_conf", field: "news_random_sources" },
  cfgLlmProviderId: { section: "basic_conf", field: "llm_provider_id" },
  cfgLlmTimeout: { section: "basic_conf", field: "llm_timeout" },
};

export const settingsPayloadGroups = {
  target: ["cfgContactAliases"],
  basic: [
    "cfgBasicTriggerMode",
    "cfgBasicFixedTimes",
    "cfgBasicShareCron",
    "cfgBasicRandomPeriods",
    "cfgBasicSmartMaxCount",
    "cfgBasicSmartQuietHours",
    "cfgBasicSmartPrompt",
    "cfgBasicCronDelay",
    "cfgBasicShareType",
    "cfgBasicShareOutputFormat",
    "cfgBasicRetentionDays",
    "cfgBasicDynamicDays",
    "cfgLlmProviderId",
    "cfgLlmTimeout",
  ],
  sequence: [
    "cfgDawnSequence",
    "cfgMorningSequence",
    "cfgForenoonSequence",
    "cfgNoonSequence",
    "cfgAfternoonSequence",
    "cfgEveningSequence",
    "cfgNightSequence",
    "cfgLateNightSequence",
  ],
  context: [
    "cfgReferenceHistoryCount",
    "cfgLifeContext",
    "cfgLifeContextGroup",
    "cfgGroupSchedule",
    "cfgChatHistory",
    "cfgDeepHistory",
    "cfgDeepHistoryHours",
    "cfgDeepHistoryMaxCount",
    "cfgPrivateHistoryCount",
    "cfgGroupIntensityCount",
    "cfgGroupShareStrategy",
    "cfgRecordMemory",
  ],
  briefing: [
    "cfgBriefing60s",
    "cfgBriefingAi",
    "cfgBriefingQzoneSync",
    "cfgBriefingScheduleMode",
    "cfgBriefingFixedTimes",
    "cfgBriefingRandomPeriods",
    "cfgBriefingCron",
    "cfgBriefingSmartMaxCount",
    "cfgBriefingSmartQuietHours",
    "cfgBriefingSmartPrompt",
    "cfgBriefingDelay",
  ],
  qzone: [
    "cfgQzoneEnabled",
    "cfgQzoneTimeout",
    "cfgQzoneTriggerMode",
    "cfgQzoneFixedTimes",
    "cfgQzoneCron",
    "cfgQzoneDelay",
    "cfgQzoneRandomPeriods",
    "cfgQzoneSmartMaxCount",
    "cfgQzoneSmartQuietHours",
    "cfgQzoneSmartPrompt",
    "cfgQzoneShareType",
    "cfgQzoneShareOutputFormat",
    "cfgQzoneImage",
    "cfgQzoneHotImage",
    "cfgQzoneImageTypes",
    "cfgQzoneAutoInteraction",
    "cfgQzoneAutoInteractionCron",
    "cfgQzoneAutoLike",
    "cfgQzoneAutoLikeLimit",
    "cfgQzoneAutoComment",
    "cfgQzoneAutoCommentLimit",
    "cfgQzoneAutoCommentPrompt",
    "cfgQzoneAutoReply",
    "cfgQzoneAutoReplyLimit",
    "cfgQzoneAutoReplyPrompt",
  ],
  qzone_sequence: [
    "cfgQzoneDawnSequence",
    "cfgQzoneMorningSequence",
    "cfgQzoneForenoonSequence",
    "cfgQzoneNoonSequence",
    "cfgQzoneAfternoonSequence",
    "cfgQzoneEveningSequence",
    "cfgQzoneNightSequence",
    "cfgQzoneLateNightSequence",
  ],
  content: ["cfgKnowledgePrefix", "cfgRecPrefix", "cfgKnowledgeCats", "cfgRecCats"],
  media: [
    "cfgAiImage",
    "cfgHotImage",
    "cfgNewsImageCleanupMax",
    "cfgPriorityText",
    "cfgAiVideo",
    "cfgSeparateMedia",
    "cfgSeparateDelay",
    "cfgRecordImageDesc",
    "cfgAppearancePrompt",
    "cfgAlwaysSelf",
    "cfgNeverSelf",
    "cfgTtsEnabled",
    "cfgAudioOnly",
    "cfgImageTypes",
    "cfgVideoTypes",
    "cfgTtsTypes",
  ],
  weixin: [
    "cfgWeixinCompress",
    "cfgWeixinMaxSide",
    "cfgWeixinMaxSize",
    "cfgWeixinTimeout",
    "cfgWeixinCleanupMax",
  ],
  news: [
    "cfgNewsApiEnabled",
    "cfgNewsApiKey",
    "cfgNewsMode",
    "cfgNewsFixedSource",
    "cfgNewsItemsCount",
    "cfgNewsShareCount",
    "cfgNewsApiTimeout",
    "cfgNewsWebSearch",
    "cfgNewsRandomSources",
  ],
};

export function settingsMappedSchemaFields() {
  const mapped = {
    root: new Set(),
    sections: new Map(),
  };
  for (const mapping of Object.values(settingsFieldSchema)) {
    if (mapping.root) {
      mapped.root.add(mapping.root);
    } else if (mapping.section && mapping.field) {
      if (!mapped.sections.has(mapping.section)) mapped.sections.set(mapping.section, new Set());
      mapped.sections.get(mapping.section).add(mapping.field);
    }
  }
  return mapped;
}
