import { MEDIA_INITIAL_LIMIT } from "./limits.js?v=20260609-media-flat";

export function createDashboardState() {
  return {
    activeView: "dashboard",
    status: null,
    configData: null,
    configDirty: false,
    configApplying: false,
    configSaving: false,
    configAutoSaveTimer: 0,
    configSaveQueued: false,
    configChangeSeq: 0,
    settingsTab: "target",
    media: [],
    mediaLoaded: false,
    mediaLimit: MEDIA_INITIAL_LIMIT,
    mediaHasMore: true,
    mediaLoading: false,
    mediaRequestSeq: 0,
    mediaRenderSignature: "",
    mediaKindFilter: "all",
    mediaTypeFilter: "all",
    mediaSelectMode: false,
    mediaSelectedIds: new Set(),
    mediaDeleting: false,
    mediaPendingDeleteKey: "",
    mediaPendingDeleteTimer: 0,
    mediaLightboxToken: 0,
    mediaLightboxItem: null,
    mediaLightboxPreviewUrl: "",
    mediaLightboxViewSource: null,
    mediaLightboxViewPromise: null,
    mediaLightboxViewLoading: false,
    mediaLightboxViewLoaded: false,
    mediaImageCache: new Map(),
    overlayLockCount: 0,
    overlayScrollY: 0,
    overlayTouchY: 0,
    mediaLightboxCloseTimer: 0,
    mediaLightboxControlTimer: 0,
    mediaLightboxSuppressCloseClick: false,
    mediaLightboxSuppressCloseTimer: 0,
    mediaLightboxControlsRevealLocked: false,
    mediaLightboxControlsHotzoneSuppressed: false,
    mediaLightboxControlsLeaveDirection: "",
    mediaLightboxControlsPointerY: null,
    mediaLightboxProgressDragging: false,
    mediaLightboxProgressPointerId: null,
    qzoneItems: [],
    qzoneDetails: new Map(),
    qzoneAccount: null,
    qzoneScope: "friends",
    qzoneTargetId: "",
    qzoneLoading: false,
    qzonePublishing: false,
    qzoneMedia: [],
    qzoneMediaReading: false,
    qzoneMessage: "",
    qzoneRetryable: false,
    qzoneHasMore: false,
    qzoneLoadingMore: false,
    qzoneNoMore: false,
    qzoneExpandedId: "",
    qzoneCommentExpandedId: "",
    qzoneCommentDrafts: new Map(),
    qzoneMenuId: "",
    qzoneDeleteConfirmId: "",
    qzoneDeletingId: "",
    qzoneSelectedId: "",
    qzoneRequestSeq: 0,
    qzoneRelationType: "care",
    qzoneRelationItems: { care: [], care_by: [] },
    qzoneRelationLoaded: { care: false, care_by: false },
    qzoneRelationLoading: false,
    qzoneRelationMessage: "",
    qzoneRelationPage: 0,
    qzoneRelationStats: null,
    qzoneRelationRequestSeq: 0,
    qzoneEntry: "",
    qzoneEntryItems: [],
    qzoneEntryKind: "",
    qzoneEntryLoading: false,
    qzoneEntryLoadingMore: false,
    qzoneEntryHasMore: false,
    qzoneEntryNextPos: 0,
    qzoneEntryMessage: "",
    qzoneEntryRequestSeq: 0,
    dashboardEventSource: null,
    dashboardEventReconnectTimer: 0,
    dashboardEventReloadTimer: 0,
    qzoneRetryTimer: 0,
    qzoneRetryCount: 0,
    qzoneTargetTimer: 0,
    textLightboxCloseTimer: 0,
    targetTab: "share",
    targetsDirty: false,
    targetsSaving: false,
    targetsSaveQueued: false,
    targetAutoSaveTimer: 0,
    targetChangeSeq: 0,
    targetCarouselIndex: 0,
    targetCarouselSignature: "",
    targetCarouselTimer: 0,
    pollTimer: 0,
    noticeTimer: 0,
    calendarPageIndex: 0,
    calendarPageCount: 0,
    calendarCarouselTimer: 0,
    calendarSignature: "",
    calendarLayoutFrame: 0,
    calendarLayoutNeedsRender: false,
    calendarStableListHeight: 0,
    calendarResizeObserver: null,
    sakuraEnabled: true,
    sakuraSaving: false,
    sakuraSynced: false,
    sakuraToggleBound: false,
    pageSwitchBound: false,
    settingsScrollFrame: 0,
    settingsScrollLockUntil: 0,
    watchedRuns: new Map(),
    bridgeReady: false,
  };
}
